/* ============================================================
   DEPLOY — Export as ZIP, deploy to Netlify/Vercel
   ============================================================ */

class DeployManager {
    constructor() {
        this.netlifyToken = '';
        this.vercelToken = '';
        this._loadSettings();
    }

    _loadSettings() {
        try {
            const saved = localStorage.getItem('zb_deploy_settings');
            if (saved) {
                const s = JSON.parse(saved);
                this.netlifyToken = s.netlifyToken || '';
                this.vercelToken = s.vercelToken || '';
            }
        } catch (e) {}
    }

    saveSettings() {
        localStorage.setItem('zb_deploy_settings', JSON.stringify({
            netlifyToken: this.netlifyToken,
            vercelToken: this.vercelToken,
        }));
    }

    /* ===== EXPORT AS ZIP ===== */
    async exportZip(files, projectName = 'zero-builder-site') {
        if (typeof JSZip === 'undefined') {
            throw new Error('JSZip not loaded. Please check your internet connection.');
        }

        const zip = new JSZip();
        
        for (const [filename, content] of Object.entries(files || {})) {
            const cleanPath = String(filename || '').replace(/^[/\\]+/, '');
            if (!cleanPath) continue;
            if (typeof content === 'string' && /^data:[^;]+;base64,/i.test(content)) {
                const base64Data = content.replace(/^data:[^;]+;base64,/i, '');
                zip.file(cleanPath, base64Data, { base64: true });
            } else {
                zip.file(cleanPath, content);
            }
        }

        // Prefer generated README if present; otherwise create a strong deploy guide
        const isNext = !!files['next.config.js'] || !!files['next.config.mjs'] || !!files['app/page.tsx'] || !!files['app/page.jsx'] || (!!files['package.json'] && files['package.json'].includes('"next"'));
        const isReact = !isNext && (!!files['src/main.jsx'] || (!!files['package.json'] && files['package.json'].includes('"react"')));
        if (!files['README.md']) {
            let readme = `# ${projectName}\n\nGenerated by ZERO-BUILDER AI — principal full-stack engineer mode.\n\n`;
            if (isNext) {
                readme += `## Next.js Full-Stack\n\nApp Router + optional Prisma/API routes.\n\n### Local setup\n\`\`\`bash\nnpm install\ncp .env.example .env\nnpx prisma generate\nnpx prisma db push\nnpm run dev\n\`\`\`\n\n### Deploy (Vercel recommended)\n1. Push repo or import the project in Vercel\n2. Set env vars from \`.env.example\`\n3. Build command: \`prisma generate && next build\`\n4. Never commit real secrets\n\n### Quality checklist\n- Marketing home + product routes\n- API validation + error states\n- Auth boundaries if enabled\n`;
            } else if (isReact) {
                readme += `## React + Vite\n\n### Local setup\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n### Production build\n\`\`\`bash\nnpm run build\nnpm run preview\n\`\`\`\n\n### Deploy\n- Netlify/Vercel static deploy from \`dist/\` after \`npm run build\`\n- Set publish directory to \`dist\`\n`;
            } else {
                readme += `## Premium Static Site\n\nOpen \`index.html\` or serve locally:\n\n\`\`\`bash\nnpx serve .\n\`\`\`\n\n### Deploy\n- Netlify drag-and-drop or CLI ZIP deploy\n- Or any static host (Cloudflare Pages, GitHub Pages, S3)\n`;
            }
            zip.file('README.md', readme);
        }

        const blob = await zip.generateAsync({ type: 'blob' });
        
        // Trigger download
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${projectName}.zip`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        return true;
    }

    /* ===== DEPLOY TO NETLIFY ===== */
    async deployToNetlify(files, siteName = 'zero-builder-site') {
        if (!this.netlifyToken) {
            throw new Error('Netlify token not configured. Go to Settings → Deploy.');
        }

        const isNext = !!files['app/page.tsx'] || !!files['app/page.jsx'] || !!files['package.json'] && files['package.json'].includes('"next"');
        const isReact = !!files['src/main.jsx'] || !!files['package.json'] && files['package.json'].includes('"react"');
        if (isReact || isNext) {
            throw new Error('Netlify direct ZIP upload only supports pre-built static websites. Download the project or deploy it through a Git-connected build pipeline.');
        }

        try {
            // Create a new site deploy via the Netlify API
            // We need to create a zip and upload it
            const zip = new JSZip();
            for (const [filename, content] of Object.entries(files)) {
                zip.file(filename, content);
            }
            const zipBlob = await zip.generateAsync({ type: 'blob' });

            // Create a new site
            const createResponse = await fetch('https://api.netlify.com/api/v1/sites', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${this.netlifyToken}`,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ name: siteName }),
            });

            if (!createResponse.ok) {
                const err = await createResponse.text();
                throw new Error(`Netlify site creation failed: ${err}`);
            }

            const site = await createResponse.json();

            // Deploy files via zip upload
            const deployResponse = await fetch(`https://api.netlify.com/api/v1/sites/${site.id}/deploys`, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${this.netlifyToken}`,
                    'Content-Type': 'application/zip',
                },
                body: zipBlob,
            });

            if (!deployResponse.ok) {
                const err = await deployResponse.text();
                throw new Error(`Netlify deploy failed: ${err}`);
            }

            const deploy = await deployResponse.json();
            return {
                success: true,
                url: deploy.ssl_url || deploy.url || `https://${site.subdomain}.netlify.app`,
                siteId: site.id,
                deployId: deploy.id,
            };
        } catch (e) {
            return { success: false, error: e.message };
        }
    }

    /* ===== DEPLOY TO VERCEL ===== */
    async deployToVercel(files, projectName = 'zero-builder-site') {
        if (!this.vercelToken) {
            throw new Error('Vercel token not configured. Go to Settings → Deploy.');
        }

        const isNext = !!files['app/page.tsx'] || !!files['app/page.jsx'] || !!files['package.json'] && files['package.json'].includes('"next"');
        const isReact = !!files['src/main.jsx'] || !!files['package.json'] && files['package.json'].includes('"react"');

        try {
            // Prepare files for Vercel API
            const vercelFiles = Object.entries(files).map(([name, content]) => ({
                file: name,
                data: btoa(unescape(encodeURIComponent(content))),
                encoding: 'base64',
            }));

            const response = await fetch('https://api.vercel.com/v13/deployments', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${this.vercelToken}`,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    name: projectName,
                    files: vercelFiles,
                    projectSettings: {
                        framework: isNext ? 'nextjs' : isReact ? 'vite' : null,
                    },
                }),
            });

            if (!response.ok) {
                const err = await response.text();
                throw new Error(`Vercel deploy failed: ${err}`);
            }

            const data = await response.json();
            return {
                success: true,
                url: `https://${data.url}`,
                deployId: data.id,
            };
        } catch (e) {
            return { success: false, error: e.message };
        }
    }

    /* ===== COPY ALL CODE ===== */
    copyAllCode(files) {
        const combined = Object.entries(files)
            .map(([name, content]) => `<!-- ===== ${name} ===== -->\n${content}`)
            .join('\n\n');
        navigator.clipboard?.writeText(combined);
        return true;
    }
}

window.DeployManager = DeployManager;
